;THIS FILE IS AUTOMATICALLY GENERATED BY BRIV GEM FARM PERFORMANCE ADDON
#include *i %A_LineFile%\..\..\IC_BrivGemFarm_Stats\IC_BrivGemFarm_Stats_Addon.ahk
#include *i %A_LineFile%\..\..\IC_EGSOverlaySwatter_Extra\IC_EGSOverlaySwatter_Addon.ahk
#include *i %A_LineFile%\..\..\IC_BrivGemFarm_LevelUp_Extra\IC_BrivGemFarm_LevelUp_Addon.ahk
#include *i %A_LineFile%\..\..\IC_GameSettingsFix_Extra\IC_GameSettingsFix_Addon.ahk
#include *i %A_LineFile%\..\..\IC_RNGWaitingRoom_Extra\IC_RNGWaitingRoom_Addon.ahk
